# Generated by Django 3.0 on 2019-12-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='babyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_color', models.CharField(max_length=64)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('delivery_time', models.CharField(max_length=64)),
                ('hospital_name', models.CharField(choices=[('A', 'Bombay Hospital Mumbai'), ('B', 'Apollo Hospital, Bandra west Mumbai')], max_length=64)),
                ('blood_group', models.CharField(max_length=64)),
                ('weight', models.CharField(max_length=64)),
                ('handicap', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=64)),
                ('aids', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=64)),
                ('doctor_name', models.CharField(max_length=64)),
                ('case_type', models.CharField(choices=[('E', 'Emergency'), ('N', 'Normal')], max_length=64)),
            ],
        ),
    ]
